import TicTacToe as ttt

tictactoe = ttt.TicTacToe()
print(tictactoe.get_field())
tictactoe.set(0, 0)
print(tictactoe.get_field())
print(tictactoe.x_turn())
tictactoe.set(2, 0)
print(tictactoe.get_field())
tictactoe.set(2, 2)
print(f"won: {tictactoe.is_won()}")
print(tictactoe.get_field())
tictactoe.set(1, 0)
tictactoe.set(0, 1)
tictactoe.set(1, 1)
tictactoe.set(2, 1)
tictactoe.set(0, 2)
print(tictactoe.is_finished())
tictactoe.set(1, 2)
print(tictactoe.is_finished())
print(tictactoe.get_field())
print(f"won: {tictactoe.is_won()}")